# SPDX-FileCopyrightText: 2026 German Aerospace Center (DLR e.V.) <https://dlr.de>
#
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
SPDX-FileCopyrightText = "2026 German Aerospace Center (DLR e.V.) <https://dlr.de>"
SPDX-License-Identifier = "CC-BY-NC-ND-3.0"
path = ["*.png"]
